# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbook',
            name='picture',
            field=models.ImageField(upload_to='media/post-book'),
        ),
    ]
